### ISSUE TITLE
Problem when "ollama pull llama 3"

### ISSUE THREAD

**Issue by diegofazio** [fcori47/basdonax-ai-rag#1]
Hola cuando trato de ejecutar el comando 

`docker exec "CONTAINERID" ollama pull llama 3 pulling 00e1317cbf74...  87% ▕█████████████   ▏ 4.0 GB/4.7 GB   39 MB/s     15s Error: write /ollama/models/blobs/sha256-00e1317cbf74d901080d7100f57580ba8dd8de57203072dc6f668324ba545f29-partial: no space left on device`

Con phi-3 funciona pq la imagen pesa menos. 
Como hago para incrementar el tamaño del volumen donde descarga la imagen?

Graciass

**Comment by phibrainDK** [comment]
afaik es un tema de espacio, podrias intentar [algo de esto... ](https://medium.com/@Rohit_Varma/effective-solutions-to-resolve-the-no-space-left-on-device-error-in-docker-741478ed8ea8)

**Comment by Nicodmx** [comment]
Me fije que en el docker la imagen de llama solo tiene 3.9gb para asignar el modelo y el modelo de llama3 pesa 4.7gb 

![image](https://github.com/fcori47/basdonax-ai-rag/assets/90804623/612327db-c1f4-4f09-9fab-2b8f93e65320)

**Comment by diegofazio** [comment]
Modificando el archivo docker-compose por lo detallado abajo me dejo descargarlo.

      volumes:
        - /ollama/models:/home/models
      environment:
        - OLLAMA_MODELS=/home/models
      deploy:
