### ISSUE TITLE
problema con carpeta compartida

### ISSUE THREAD

**Issue by anibalardid** [fcori47/basdonax-ai-rag#9]
Hola !  Yo uso MacOS (ultima version, y ultima version de docker desktop)

al ejecutar el compose tengo el error de que no se pudo montar la carpeta ollama/models

![image](https://github.com/fcori47/basdonax-ai-rag/assets/1769919/2409a4dc-59de-456f-a1cc-bd7291e17eee)

Al agregarla a las settngs del docker me da error 

![image](https://github.com/fcori47/basdonax-ai-rag/assets/1769919/0705ff82-beae-4888-bbe7-3b3282092b55)

Alguna idea ?

**Comment by anibalardid** [comment]
Solucionado, el problema es el path, hay que corregirlo por una carpeta/directorio que exista en nuestra compu.

**Comment by anibalardid** [comment]
se corrige el docker-compose.yml

**Comment by CarlosPinedaT** [comment]
@anibalardid puedes mostrar su docker-compose .?
